In [1]:
#First Feature
weather = ['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy',
           'Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']

In [2]:
#Second Feature
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild',
       'Mild','Hot','Mild']

In [3]:
# label or target varible
play = ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [4]:
#import labelEncoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [5]:
#creating labelEncoder
weather_encoded = le.fit_transform(weather)

In [6]:
weather_encoded

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1], dtype=int64)

In [7]:
temp_encoded = le.fit_transform(temp)
temp_encoded

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 1, 2], dtype=int64)

In [8]:
play_encoded = le.fit_transform(play)
play_encoded

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [13]:
feature = list(zip(weather_encoded,temp_encoded)) # combining weather and temp in list of tuple

In [14]:
feature

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 1),
 (0, 2)]

In [36]:
feature.shape
feature.reshape(-1,1)

AttributeError: 'list' object has no attribute 'shape'

In [18]:
from sklearn.neighbors import KNeighborsClassifier
KNC=KNeighborsClassifier(n_neighbors=3) # K is n_neighbors

In [34]:
#Train the model using the training sets
KNC.fit([[feature]],[[play_encoded]])

ValueError: Found array with dim 4. Estimator expected <= 2.

In [32]:
predict = KNC.predict([[0,2]])

NotFittedError: This KNeighborsClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.